[TITO-17]
monutech/tito-taco-shop pull request #18
Opened 2022-08-16 23:18 UTC by whitneyjsmith

2022-08-17 23:02 UTC, dahjah commented
Looks awesome so far!

As we were discussing during the meeting, we decided that I think we will actually want to remove the attribute_bases manytomany field on the Product. :)

In addition to that change, can you also add __str__ methods to the models, and then use filter_horizontal in the admin registration for Product?
(That would look something like this:

`
@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    filter_vertical = ('attributes',)
`
)

2022-08-17 23:03 UTC, kpavia reviewed
I second DJ's comment!
Looks good but we just had these things occur to us while checking it out and discussing.

2022-08-17 23:04 UTC, dahjah requested changes

2022-08-17 23:04 UTC, dahjah commented on products/admin.py
>  admin.site.register(Product)
Would you mind updating this to look something like this? 

```
@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    filter_vertical = ('attributes',)
```

2022-08-17 23:04 UTC, dahjah commented on products/models.py
> +
Can you add some __str__ methods here? :)

2022-08-22 20:54 UTC, whitneyjsmith commented
@dahjah @kpavia awesome I made those changes. Thanks for reviewing my code

2022-08-24 22:06 UTC, dahjah approved these changes
Looks great!

2022-08-24 22:36 UTC, kpavia approved these changes

2022-08-24 22:36 UTC, merged